Updated Kotlin
TeamSubstratum/SubstratumThemeTemplate pull request #85
Opened 2018-10-03 20:32 UTC by gcantoni

Signed-off-by: Giorgio Cantoni <giorgio.canto98@gmail.com>

2018-10-03 20:32 UTC, gcantoni commented
@gcantoni @svandasek

2018-10-04 19:16 UTC, jansvanda commented
Merge pls, will save noobs like me time

2018-10-04 19:18 UTC, MSF-Jarvis commented
@jansvanda ?
@gcantoni We follow AS Canary, which ships plugin 1.2.71

2018-10-04 19:39 UTC, gcantoni commented
@MSF-Jarvis as @jansvanda said in group he got an error during building the theme related to the grade kotlin version. It will be helpful to other themers facing that.

2018-10-04 19:40 UTC, msfjarvis requested changes

2018-10-04 19:40 UTC, MSF-Jarvis commented on build.gradle
> +    ext.kotlin_version = '1.2.51'
1.2.71

2018-10-04 19:44 UTC, gcantoni commented
@MSF-Jarvis merge 😄

2018-10-04 19:46 UTC, merged